apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-workload
  labels:
    app: sample-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-workload
  template:
    metadata:
      labels:
        app: sample-workload
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80